export const SCAN_CONFIG = {
  MAX_IMAGE_SIZE_BYTES: 5 * 1024 * 1024,
  ALLOWED_MIME_TYPES: ['image/jpeg', 'image/png'],
  COMPRESSED_MAX_WIDTH: 1024,
  COMPRESSED_JPEG_QUALITY: 75,
  GEMINI_MODEL: 'gemini-2.0-flash',
  GEMINI_MAX_TOKENS: 1024,
  REQUEST_TIMEOUT_MS: 30000,
};
